#!/bin/sh
TCL_VERSIONS="8.5 8.6"
TCLSH=""

for VERSION in $TCL_VERSIONS; do
	TCL=`which tclsh$VERSION 2>/dev/null` && TCLSH=$TCL
done

if [ -z $TCLSH ]
then
    echo "您需要tcl 8.5或更新版本才能运行Redis测试" 
    exit 1
fi
$TCLSH tests/test_helper.tcl $*
